plugin:
  name: test-spring-web-plugin
  group: io.zephyr.spring
  version: 1.0.0
  order: 1
  type: plugin
  description: Plugin supporting extension points for Spring Web.
  dependencies:
    - dependency:
        type: library
        required: true
        group: io.zephyr.spring
        version: 1.0.0
        name: spring-web-plugin
