name: Prepare Zephyr Release
on:
  push:
    tags:
        - 't*'

jobs:
  build:
    runs-on: ubuntu-latest


    #################   Set up Environment  #################
    #
    #   This is where we set the new MAJOR and MINOR versions
    #   for a series of releases.  This must be updated both
    #   here and in release.yml
    #
    #################   Set up Environment  #################

    env:
      CURRENT_MAJOR_VERSION: 2
      CURRENT_MINOR_VERSION: 0

    #################   Overview of Build Process   #################
    #   Note:  this is documented fully at
    #   https://github.com/sunshower-io/zephyr/build.md
    #
    #   Versions:  most/all component versions should be stored in
    #   bom/imported/pom.xml
    #
    #   Released versions:  All exported component versions should be
    #   stored in bom/exported/pom.xml
    #
    #   Odd dependency notes:
    #   Project path: tools/zephyr-bundle/native-packages/(windows,linux,mac)
    #   Notes:  These projects depend on warp (https://github.com/dgiagio/warp/releases)
    #
    #
    #
    #
    #################   Overview of Build Process   #################

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate Build Number
        id: buildnumber
        uses: einaregilsson/build-number@v2
        with:
          token: ${{ secrets.github_token }}
          prefix: zephyr




      - name: Set Final Version Number
        id: finalVersion
        run: |
          echo '::set-output name=result::$CURRENT_MAJOR_VERSION.$CURRENT_MINOR_VERSION.$BUILD_NUMBER.Final'


      - name: Generate Next Number
        id: nextbuildnumber
        uses: einaregilsson/build-number@v2
        with:
          token: ${{ secrets.github_token }}
          prefix: zephyr

      - name: Set Next Snapshot Version Number
        id: snapshotVersion
        run: |
          echo '::set-output name=result::$CURRENT_MAJOR_VERSION.$CURRENT_MINOR_VERSION.$BUILD_NUMBER-SNAPSHOT'

      - name: Increment Bills-of-Materials
        run: |
          mvn versions:set -DnewVersion=${{ steps.finalVersion.outputs.result }} -f bom
          mvn clean install -f bom


      - name: Increment Zephyr Maven Plugin Version
        run: >-
          mvn versions:set
          -DnewVersion=${{ steps.finalVersion.outputs.result }}
          -f tools/zephyr-maven-plugin
          --settings bom/settings/settings.xml

      - name: Increment Zephyr Build Number
        uses: eskatos/gradle-command-action@v1
        env:
          JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
        with:
          gradle-version: 6.0.1
          arguments: >-
            setVersion -DzephyrRelease=true
            -PmavenRepositoryUsername=${{secrets.MAVEN_REPOSITORY_USERNAME}}
            -PmavenRepositoryPassword=${{secrets.MAVEN_REPOSITORY_PASSWORD}}
            -PmavenRepositoryUrl=${{secrets.MAVEN_REPOSITORY_URL}}

      - name: Deploy Bills-Of-Materials
        run: >-
          mvn install deploy -f bom
          --settings bom/settings/settings.xml
          -Dsunshower-repo.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -Dsunshower-repo.password=${{secrets.MAVEN_REPOSITORY_PASSWORD}} -e




      - name: Build Zephyr Projects
        uses: eskatos/gradle-command-action@v1
        env:
          JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
        with:
          gradle-version: 6.0.1
          arguments: >-
            assemble build sA publish -i
            -PmavenRepositoryUsername=${{secrets.MAVEN_REPOSITORY_USERNAME}}
            -PmavenRepositoryPassword=${{secrets.MAVEN_REPOSITORY_PASSWORD}}
            -PmavenRepositoryUrl=${{secrets.MAVEN_RELEASE_URL}} --stacktrace


      #################   Deploy Zephyr Maven Plugin #################
      #
      #   build and deploy the zephyr maven plugin.
      #
      #   Note:  This must happen after "Build Zephyr Projects" action
      #
      #################   Deploy Zephyr Maven Plugin #################

      - name: Deploy Zephyr Maven Plugin
        run: >-
          mvn install deploy -f tools/zephyr-maven-plugin
          --settings bom/settings/settings.xml
          -Dsunshower-repo.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -Dsunshower-repo.password=${{secrets.MAVEN_REPOSITORY_PASSWORD}} -e

      - name: Commit Version Changes
        run: |
          git config --local user.email "build@sunshower.io"
          git config --local user.name "build"
          git commit -am "Final Release [tag: final, version: ${{steps.finalVersion.outputs.result}}]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git tag -a v${{ steps.finalVersion.outputs.result }} -m "Releasing ${{ steps.finalVersion.outputs.result }}"
          git push origin v${{ steps.finalVersion.outputs.result }}



      #################   Rev Snapshots     #################



      - name: Increment Bills-of-Materials to Snapshots
        run: |
          mvn versions:set -DnewVersion=${{ steps.snapshotVersion.outputs.result }} -f bom
          mvn clean install -f bom

      - name: Increment Zephyr Maven Plugin Version
        run: >-
          mvn versions:set -DnewVersion=${{ steps.snapshotVersion.outputs.result }}
          -f tools/zephyr-maven-plugin

      - name: Increment Zephyr Build Number to Snapshot
        uses: eskatos/gradle-command-action@v1
        env:
          JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
        with:
          gradle-version: 6.0.1
          arguments: >-
            setVersion -PmavenRepositoryUsername=${{secrets.MAVEN_REPOSITORY_USERNAME}}
            -PmavenRepositoryPassword=${{secrets.MAVEN_REPOSITORY_PASSWORD}}
            -PmavenRepositoryUrl=${{secrets.MAVEN_REPOSITORY_URL}}

      - name: Deploy Bills-Of-Materials
        run: >-
          mvn install deploy -f bom
          --settings bom/settings/settings.xml
          -Dsunshower-repo.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -Dsunshower-repo.password=${{secrets.MAVEN_REPOSITORY_PASSWORD}} -e



      - name: Build Zephyr Projects
        uses: eskatos/gradle-command-action@v1
        env:
          JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
        with:
          gradle-version: 6.0.1
          arguments: >-
            assemble build sA publish -i
            -PmavenRepositoryUsername=${{secrets.MAVEN_REPOSITORY_USERNAME}}
            -PmavenRepositoryPassword=${{secrets.MAVEN_REPOSITORY_PASSWORD}}
            -PmavenRepositoryUrl=${{secrets.MAVEN_REPOSITORY_URL}} --stacktrace


      - name: Deploy Zephyr Maven Plugin
        run: >-
          mvn install deploy -f tools/zephyr-maven-plugin
          --settings bom/settings/settings.xml
          -Dsunshower-repo.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -Dsunshower-repo.password=${{secrets.MAVEN_REPOSITORY_PASSWORD}} -e

      - name: Commit Version Changes and Release
        run: |
          git config --local user.email "build@sunshower.io"
          git config --local user.name "build"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Releasing new Snapshot [tag: snapshot]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
