name: Perform Zephyr Release
on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    runs-on: ubuntu-latest

    #################   Set Up Environment  #################

    env:
      CURRENT_MAJOR_VERSION: 2
      CURRENT_MINOR_VERSION: 0


    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11


      - name: Build Zephyr Artifacts
        uses: eskatos/gradle-command-action@v1
        env:
          JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
        with:
          gradle-version: 6.0.1
          arguments: >-
            assemble build sA -i
            -PmavenRepositoryUsername=${{secrets.MAVEN_REPOSITORY_USERNAME}}
            -PmavenRepositoryPassword=${{secrets.MAVEN_REPOSITORY_PASSWORD}}
            -PmavenRepositoryUrl=${{secrets.MAVEN_RELEASE_URL}} --stacktrace -x test


      - uses: actions/upload-artifact@v2
        with:
          name: zephyr-main
          path: zephyr-main/build/distributions/**/*.zip

      - name: get commit message
        run: echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})

      - name: Perform Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release:
            ${{ env.commitmsg }}
          draft: false
          prerelease: false