name: Create Zephyr Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Generate Build Number
        id: buildnumber
        uses: einaregilsson/build-number@v2
        with:
          token: ${{ secrets.github_token }}
          prefix: zephyr
      - name: Increment Bills-of-Materials
        run: |
          mvn versions:set -DnewVersion=${{secrets.CURRENT_VERSION}}.$BUILD_NUMBER.Final -f bom

      - name: Deploy Bills-Of-Materials
        run: mvn install deploy -f bom --settings bom/settings/settings.xml -Dsunshower-repo.username=${{secrets.MAVEN_REPOSITORY_USERNAME}} -Dsunshower-repo.password=${{secrets.MAVEN_REPOSITORY_PASSWORD}}



